# Generated by Django 3.2.9 on 2021-11-05 04:53

import django.core.validators
from django.db import migrations, models
import msgserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8), msgserver.models.validate_key])),
                ('message', models.CharField(max_length=160, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(160)])),
            ],
        ),
    ]
